// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: muallimah-submodule/protos/book.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Price       float32  `protobuf:"fixed32,3,opt,name=Price,proto3" json:"Price,omitempty"`
	PictureUrls []string `protobuf:"bytes,4,rep,name=PictureUrls,proto3" json:"PictureUrls,omitempty"`
}

func (x *BookCreate) Reset() {
	*x = BookCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_book_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookCreate) ProtoMessage() {}

func (x *BookCreate) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_book_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookCreate.ProtoReflect.Descriptor instead.
func (*BookCreate) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_book_proto_rawDescGZIP(), []int{0}
}

func (x *BookCreate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookCreate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BookCreate) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookCreate) GetPictureUrls() []string {
	if x != nil {
		return x.PictureUrls
	}
	return nil
}

type BookUpt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string  `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Description string  `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Price       float32 `protobuf:"fixed32,3,opt,name=Price,proto3" json:"Price,omitempty"`
}

func (x *BookUpt) Reset() {
	*x = BookUpt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_book_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookUpt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookUpt) ProtoMessage() {}

func (x *BookUpt) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_book_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookUpt.ProtoReflect.Descriptor instead.
func (*BookUpt) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookUpt) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookUpt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BookUpt) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BookUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Body *BookUpt `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *BookUpdate) Reset() {
	*x = BookUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_book_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookUpdate) ProtoMessage() {}

func (x *BookUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_book_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookUpdate.ProtoReflect.Descriptor instead.
func (*BookUpdate) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_book_proto_rawDescGZIP(), []int{2}
}

func (x *BookUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookUpdate) GetBody() *BookUpt {
	if x != nil {
		return x.Body
	}
	return nil
}

type BookPicture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId     string `protobuf:"bytes,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	PictureUrl string `protobuf:"bytes,2,opt,name=PictureUrl,proto3" json:"PictureUrl,omitempty"`
}

func (x *BookPicture) Reset() {
	*x = BookPicture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_book_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookPicture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookPicture) ProtoMessage() {}

func (x *BookPicture) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_book_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookPicture.ProtoReflect.Descriptor instead.
func (*BookPicture) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_book_proto_rawDescGZIP(), []int{3}
}

func (x *BookPicture) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *BookPicture) GetPictureUrl() string {
	if x != nil {
		return x.PictureUrl
	}
	return ""
}

type BookGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title       string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Price       float32  `protobuf:"fixed32,4,opt,name=Price,proto3" json:"Price,omitempty"`
	PictureUrls []string `protobuf:"bytes,5,rep,name=PictureUrls,proto3" json:"PictureUrls,omitempty"`
	CreatedAt   string   `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
}

func (x *BookGet) Reset() {
	*x = BookGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_book_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookGet) ProtoMessage() {}

func (x *BookGet) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_book_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookGet.ProtoReflect.Descriptor instead.
func (*BookGet) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_book_proto_rawDescGZIP(), []int{4}
}

func (x *BookGet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookGet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookGet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BookGet) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookGet) GetPictureUrls() []string {
	if x != nil {
		return x.PictureUrls
	}
	return nil
}

func (x *BookGet) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type BookFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string      `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	PriceFrom  float32     `protobuf:"fixed32,2,opt,name=PriceFrom,proto3" json:"PriceFrom,omitempty"`
	PriceTo    float32     `protobuf:"fixed32,3,opt,name=PriceTo,proto3" json:"PriceTo,omitempty"`
	Pagination *Pagination `protobuf:"bytes,4,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
}

func (x *BookFilter) Reset() {
	*x = BookFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_book_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookFilter) ProtoMessage() {}

func (x *BookFilter) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_book_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookFilter.ProtoReflect.Descriptor instead.
func (*BookFilter) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_book_proto_rawDescGZIP(), []int{5}
}

func (x *BookFilter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookFilter) GetPriceFrom() float32 {
	if x != nil {
		return x.PriceFrom
	}
	return 0
}

func (x *BookFilter) GetPriceTo() float32 {
	if x != nil {
		return x.PriceTo
	}
	return 0
}

func (x *BookFilter) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type BookList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books      []*BookGet  `protobuf:"bytes,1,rep,name=Books,proto3" json:"Books,omitempty"`
	TotalCount int64       `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	Pagination *Pagination `protobuf:"bytes,3,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
}

func (x *BookList) Reset() {
	*x = BookList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_book_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookList) ProtoMessage() {}

func (x *BookList) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_book_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookList.ProtoReflect.Descriptor instead.
func (*BookList) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_book_proto_rawDescGZIP(), []int{6}
}

func (x *BookList) GetBooks() []*BookGet {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *BookList) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *BookList) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_muallimah_submodule_protos_book_proto protoreflect.FileDescriptor

var file_muallimah_submodule_protos_book_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6d, 0x75, 0x61, 0x6c, 0x6c, 0x69, 0x6d, 0x61, 0x68, 0x2d, 0x73, 0x75, 0x62, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x6f, 0x6f,
	0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a,
	0x27, 0x6d, 0x75, 0x61, 0x6c, 0x6c, 0x69, 0x6d, 0x61, 0x68, 0x2d, 0x73, 0x75, 0x62, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x55,
	0x72, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x55, 0x72, 0x6c, 0x73, 0x22, 0x57, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6b, 0x55, 0x70,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22,
	0x41, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x55, 0x70, 0x74, 0x52, 0x04, 0x42, 0x6f,
	0x64, 0x79, 0x22, 0x45, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x55, 0x72, 0x6c, 0x22, 0xa7, 0x01, 0x0a, 0x07, 0x42, 0x6f,
	0x6f, 0x6b, 0x47, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x55, 0x72,
	0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x63, 0x65, 0x54,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x50, 0x72, 0x69, 0x63, 0x65, 0x54, 0x6f,
	0x12, 0x32, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x85, 0x01, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x25, 0x0a, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x47, 0x65,
	0x74, 0x52, 0x05, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xd9, 0x02, 0x0a,
	0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x1a, 0x0c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x0c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0a,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79,
	0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x47, 0x65, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x18, 0x5a, 0x16, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_muallimah_submodule_protos_book_proto_rawDescOnce sync.Once
	file_muallimah_submodule_protos_book_proto_rawDescData = file_muallimah_submodule_protos_book_proto_rawDesc
)

func file_muallimah_submodule_protos_book_proto_rawDescGZIP() []byte {
	file_muallimah_submodule_protos_book_proto_rawDescOnce.Do(func() {
		file_muallimah_submodule_protos_book_proto_rawDescData = protoimpl.X.CompressGZIP(file_muallimah_submodule_protos_book_proto_rawDescData)
	})
	return file_muallimah_submodule_protos_book_proto_rawDescData
}

var file_muallimah_submodule_protos_book_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_muallimah_submodule_protos_book_proto_goTypes = []interface{}{
	(*BookCreate)(nil),  // 0: protos.BookCreate
	(*BookUpt)(nil),     // 1: protos.BookUpt
	(*BookUpdate)(nil),  // 2: protos.BookUpdate
	(*BookPicture)(nil), // 3: protos.BookPicture
	(*BookGet)(nil),     // 4: protos.BookGet
	(*BookFilter)(nil),  // 5: protos.BookFilter
	(*BookList)(nil),    // 6: protos.BookList
	(*Pagination)(nil),  // 7: protos.Pagination
	(*ById)(nil),        // 8: protos.ById
	(*Void)(nil),        // 9: protos.Void
}
var file_muallimah_submodule_protos_book_proto_depIdxs = []int32{
	1,  // 0: protos.BookUpdate.Body:type_name -> protos.BookUpt
	7,  // 1: protos.BookFilter.Pagination:type_name -> protos.Pagination
	4,  // 2: protos.BookList.Books:type_name -> protos.BookGet
	7,  // 3: protos.BookList.Pagination:type_name -> protos.Pagination
	0,  // 4: protos.BookService.CreateBook:input_type -> protos.BookCreate
	2,  // 5: protos.BookService.UpdateBook:input_type -> protos.BookUpdate
	8,  // 6: protos.BookService.DeleteBook:input_type -> protos.ById
	5,  // 7: protos.BookService.ListBooks:input_type -> protos.BookFilter
	8,  // 8: protos.BookService.GetBook:input_type -> protos.ById
	3,  // 9: protos.BookService.AddPicture:input_type -> protos.BookPicture
	3,  // 10: protos.BookService.DeletePicture:input_type -> protos.BookPicture
	9,  // 11: protos.BookService.CreateBook:output_type -> protos.Void
	9,  // 12: protos.BookService.UpdateBook:output_type -> protos.Void
	9,  // 13: protos.BookService.DeleteBook:output_type -> protos.Void
	6,  // 14: protos.BookService.ListBooks:output_type -> protos.BookList
	4,  // 15: protos.BookService.GetBook:output_type -> protos.BookGet
	9,  // 16: protos.BookService.AddPicture:output_type -> protos.Void
	9,  // 17: protos.BookService.DeletePicture:output_type -> protos.Void
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_muallimah_submodule_protos_book_proto_init() }
func file_muallimah_submodule_protos_book_proto_init() {
	if File_muallimah_submodule_protos_book_proto != nil {
		return
	}
	file_muallimah_submodule_protos_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_muallimah_submodule_protos_book_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_book_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookUpt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_book_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_book_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookPicture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_book_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_book_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_book_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_muallimah_submodule_protos_book_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_muallimah_submodule_protos_book_proto_goTypes,
		DependencyIndexes: file_muallimah_submodule_protos_book_proto_depIdxs,
		MessageInfos:      file_muallimah_submodule_protos_book_proto_msgTypes,
	}.Build()
	File_muallimah_submodule_protos_book_proto = out.File
	file_muallimah_submodule_protos_book_proto_rawDesc = nil
	file_muallimah_submodule_protos_book_proto_goTypes = nil
	file_muallimah_submodule_protos_book_proto_depIdxs = nil
}
