basePath: /
definitions:
  genproto.Category:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  genproto.CategoryCreateReq:
    properties:
      name:
        type: string
    type: object
  genproto.CategoryListRes:
    properties:
      categories:
        items:
          $ref: '#/definitions/genproto.Category'
        type: array
      pagination:
        $ref: '#/definitions/genproto.Pagination'
      total_count:
        type: integer
    type: object
  genproto.CategoryUpt:
    properties:
      name:
        type: string
    type: object
  genproto.MaterialCreateReq:
    properties:
      description:
        type: string
      lesson_id:
        type: string
      resource_url:
        type: string
      title:
        type: string
    type: object
  genproto.MaterialGetRes:
    properties:
      description:
        type: string
      id:
        type: string
      lesson_id:
        type: string
      resource_url:
        type: string
      title:
        type: string
    type: object
  genproto.MaterialListRes:
    properties:
      materials:
        items:
          $ref: '#/definitions/genproto.MaterialGetRes'
        type: array
    type: object
  genproto.MaterialUpdate:
    properties:
      description:
        type: string
      resource_url:
        type: string
      title:
        type: string
    type: object
  genproto.Pagination:
    properties:
      limit:
        type: integer
      offset:
        type: integer
    type: object
info:
  contact: {}
  description: API for Instant Delivery resources
  title: Finance Tracker API Documentation
  version: "1.0"
paths:
  /categories/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a category by its ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Category deleted successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "404":
          description: Category not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete Category
      tags:
      - Category
    get:
      consumes:
      - application/json
      description: Retrieve a category by its ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Category details
          schema:
            $ref: '#/definitions/genproto.Category'
        "400":
          description: Invalid request
          schema:
            type: string
        "404":
          description: Category not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get Category
      tags:
      - Category
    put:
      consumes:
      - application/json
      description: Update an existing category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      - description: Category data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/genproto.CategoryUpt'
      produces:
      - application/json
      responses:
        "200":
          description: Category updated successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update Category
      tags:
      - Category
  /categories/create:
    post:
      consumes:
      - application/json
      description: Create a new category
      parameters:
      - description: Category data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/genproto.CategoryCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: Category created successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Create Category
      tags:
      - Category
  /categories/list:
    get:
      consumes:
      - application/json
      description: Retrieve a list of categories
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of categories
          schema:
            $ref: '#/definitions/genproto.CategoryListRes'
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: List Categories
      tags:
      - Category
  /materials/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a material by its ID
      parameters:
      - description: Material ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Material deleted successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "404":
          description: Material not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete Material
      tags:
      - Material
    get:
      consumes:
      - application/json
      description: Retrieve a material by its ID
      parameters:
      - description: Material ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Material details
          schema:
            $ref: '#/definitions/genproto.MaterialGetRes'
        "400":
          description: Invalid request
          schema:
            type: string
        "404":
          description: Material not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get Material
      tags:
      - Material
    put:
      consumes:
      - application/json
      description: Update an existing material
      parameters:
      - description: Material ID
        in: path
        name: id
        required: true
        type: string
      - description: Material data
        in: body
        name: material
        required: true
        schema:
          $ref: '#/definitions/genproto.MaterialUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: Material updated successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update Material
      tags:
      - Material
  /materials/create:
    post:
      consumes:
      - application/json
      description: Create a new material
      parameters:
      - description: Material data
        in: body
        name: material
        required: true
        schema:
          $ref: '#/definitions/genproto.MaterialCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: Material created successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Create Material
      tags:
      - Material
  /materials/list:
    get:
      consumes:
      - application/json
      description: Retrieve a list of materials
      parameters:
      - description: Lesson ID
        in: query
        name: lesson_id
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of materials
          schema:
            $ref: '#/definitions/genproto.MaterialListRes'
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: List Materials
      tags:
      - Material
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
