// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.1
// source: muallimah-submodule/protos/additional_materials.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaterialCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LessonId    string `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	ResourceUrl string `protobuf:"bytes,2,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *MaterialCreateReq) Reset() {
	*x = MaterialCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaterialCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialCreateReq) ProtoMessage() {}

func (x *MaterialCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialCreateReq.ProtoReflect.Descriptor instead.
func (*MaterialCreateReq) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_additional_materials_proto_rawDescGZIP(), []int{0}
}

func (x *MaterialCreateReq) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *MaterialCreateReq) GetResourceUrl() string {
	if x != nil {
		return x.ResourceUrl
	}
	return ""
}

func (x *MaterialCreateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MaterialCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type MaterialGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LessonId    string `protobuf:"bytes,2,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	ResourceUrl string `protobuf:"bytes,3,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Title       string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *MaterialGetRes) Reset() {
	*x = MaterialGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaterialGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialGetRes) ProtoMessage() {}

func (x *MaterialGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialGetRes.ProtoReflect.Descriptor instead.
func (*MaterialGetRes) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_additional_materials_proto_rawDescGZIP(), []int{1}
}

func (x *MaterialGetRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MaterialGetRes) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *MaterialGetRes) GetResourceUrl() string {
	if x != nil {
		return x.ResourceUrl
	}
	return ""
}

func (x *MaterialGetRes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MaterialGetRes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type MaterialUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceUrl string `protobuf:"bytes,1,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *MaterialUpdate) Reset() {
	*x = MaterialUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaterialUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialUpdate) ProtoMessage() {}

func (x *MaterialUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialUpdate.ProtoReflect.Descriptor instead.
func (*MaterialUpdate) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_additional_materials_proto_rawDescGZIP(), []int{2}
}

func (x *MaterialUpdate) GetResourceUrl() string {
	if x != nil {
		return x.ResourceUrl
	}
	return ""
}

func (x *MaterialUpdate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MaterialUpdate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type MaterialUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body *MaterialUpdate `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *MaterialUpdateReq) Reset() {
	*x = MaterialUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaterialUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialUpdateReq) ProtoMessage() {}

func (x *MaterialUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialUpdateReq.ProtoReflect.Descriptor instead.
func (*MaterialUpdateReq) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_additional_materials_proto_rawDescGZIP(), []int{3}
}

func (x *MaterialUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MaterialUpdateReq) GetBody() *MaterialUpdate {
	if x != nil {
		return x.Body
	}
	return nil
}

type MaterialListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LessonId   string      `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Pagination *Pagination `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *MaterialListReq) Reset() {
	*x = MaterialListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaterialListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialListReq) ProtoMessage() {}

func (x *MaterialListReq) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialListReq.ProtoReflect.Descriptor instead.
func (*MaterialListReq) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_additional_materials_proto_rawDescGZIP(), []int{4}
}

func (x *MaterialListReq) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *MaterialListReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type MaterialListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Materials []*MaterialGetRes `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
}

func (x *MaterialListRes) Reset() {
	*x = MaterialListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaterialListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialListRes) ProtoMessage() {}

func (x *MaterialListRes) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_additional_materials_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialListRes.ProtoReflect.Descriptor instead.
func (*MaterialListRes) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_additional_materials_proto_rawDescGZIP(), []int{5}
}

func (x *MaterialListRes) GetMaterials() []*MaterialGetRes {
	if x != nil {
		return x.Materials
	}
	return nil
}

var File_muallimah_submodule_protos_additional_materials_proto protoreflect.FileDescriptor

var file_muallimah_submodule_protos_additional_materials_proto_rawDesc = []byte{
	0x0a, 0x35, 0x6d, 0x75, 0x61, 0x6c, 0x6c, 0x69, 0x6d, 0x61, 0x68, 0x2d, 0x73, 0x75, 0x62, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x64, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a,
	0x27, 0x6d, 0x75, 0x61, 0x6c, 0x6c, 0x69, 0x6d, 0x61, 0x68, 0x2d, 0x73, 0x75, 0x62, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x11, 0x4d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b,
	0x0a, 0x09, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x98, 0x01, 0x0a, 0x0e, 0x4d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x73,
	0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x6b, 0x0a, 0x0e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f,
	0x0a, 0x11, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22,
	0x62, 0x0a, 0x0f, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x32, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x47, 0x0a, 0x0f, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x32, 0xad, 0x02, 0x0a,
	0x0f, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x39, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x12, 0x39, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x0e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x41, 0x0a, 0x0d, 0x4c, 0x69, 0x73,
	0x74, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x42, 0x18, 0x5a, 0x16,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_muallimah_submodule_protos_additional_materials_proto_rawDescOnce sync.Once
	file_muallimah_submodule_protos_additional_materials_proto_rawDescData = file_muallimah_submodule_protos_additional_materials_proto_rawDesc
)

func file_muallimah_submodule_protos_additional_materials_proto_rawDescGZIP() []byte {
	file_muallimah_submodule_protos_additional_materials_proto_rawDescOnce.Do(func() {
		file_muallimah_submodule_protos_additional_materials_proto_rawDescData = protoimpl.X.CompressGZIP(file_muallimah_submodule_protos_additional_materials_proto_rawDescData)
	})
	return file_muallimah_submodule_protos_additional_materials_proto_rawDescData
}

var file_muallimah_submodule_protos_additional_materials_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_muallimah_submodule_protos_additional_materials_proto_goTypes = []any{
	(*MaterialCreateReq)(nil), // 0: protos.MaterialCreateReq
	(*MaterialGetRes)(nil),    // 1: protos.MaterialGetRes
	(*MaterialUpdate)(nil),    // 2: protos.MaterialUpdate
	(*MaterialUpdateReq)(nil), // 3: protos.MaterialUpdateReq
	(*MaterialListReq)(nil),   // 4: protos.MaterialListReq
	(*MaterialListRes)(nil),   // 5: protos.MaterialListRes
	(*Pagination)(nil),        // 6: protos.Pagination
	(*ById)(nil),              // 7: protos.ById
	(*Void)(nil),              // 8: protos.Void
}
var file_muallimah_submodule_protos_additional_materials_proto_depIdxs = []int32{
	2, // 0: protos.MaterialUpdateReq.body:type_name -> protos.MaterialUpdate
	6, // 1: protos.MaterialListReq.pagination:type_name -> protos.Pagination
	1, // 2: protos.MaterialListRes.materials:type_name -> protos.MaterialGetRes
	0, // 3: protos.MaterialService.CreateMaterial:input_type -> protos.MaterialCreateReq
	7, // 4: protos.MaterialService.GetMaterial:input_type -> protos.ById
	3, // 5: protos.MaterialService.UpdateMaterial:input_type -> protos.MaterialUpdateReq
	7, // 6: protos.MaterialService.DeleteMaterial:input_type -> protos.ById
	4, // 7: protos.MaterialService.ListMaterials:input_type -> protos.MaterialListReq
	8, // 8: protos.MaterialService.CreateMaterial:output_type -> protos.Void
	1, // 9: protos.MaterialService.GetMaterial:output_type -> protos.MaterialGetRes
	8, // 10: protos.MaterialService.UpdateMaterial:output_type -> protos.Void
	8, // 11: protos.MaterialService.DeleteMaterial:output_type -> protos.Void
	5, // 12: protos.MaterialService.ListMaterials:output_type -> protos.MaterialListRes
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_muallimah_submodule_protos_additional_materials_proto_init() }
func file_muallimah_submodule_protos_additional_materials_proto_init() {
	if File_muallimah_submodule_protos_additional_materials_proto != nil {
		return
	}
	file_muallimah_submodule_protos_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_muallimah_submodule_protos_additional_materials_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MaterialCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_additional_materials_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MaterialGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_additional_materials_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MaterialUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_additional_materials_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MaterialUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_additional_materials_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MaterialListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_additional_materials_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*MaterialListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_muallimah_submodule_protos_additional_materials_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_muallimah_submodule_protos_additional_materials_proto_goTypes,
		DependencyIndexes: file_muallimah_submodule_protos_additional_materials_proto_depIdxs,
		MessageInfos:      file_muallimah_submodule_protos_additional_materials_proto_msgTypes,
	}.Build()
	File_muallimah_submodule_protos_additional_materials_proto = out.File
	file_muallimah_submodule_protos_additional_materials_proto_rawDesc = nil
	file_muallimah_submodule_protos_additional_materials_proto_goTypes = nil
	file_muallimah_submodule_protos_additional_materials_proto_depIdxs = nil
}
