FROM golang:1.22.5 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o shop_service ./cmd/app

FROM alpine:latest

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=builder /app/shop_service .

COPY .env .env 

RUN chmod +x shop_service

EXPOSE 50051

CMD ["./shop_service"]
