# version: '4.0'

services:
  auth-service:
    container_name: auth_service 
    build: ./
    ports:
      - "8088:8088"
    networks:
      - muallimah
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - muallimah


networks:
  muallimah:
    external: true
    name: muallimah
    driver: bridge

volumes:
  db:
  redis-data: