version: '3.9'

services:
  gateway:
    container_name: gateway
    build: .
    ports:
      - "5050:5050"
    networks:
      - muallimah
    environment:
      - KAFKA_BROKER=kafka:9092      

networks:
  muallimah:
      external: true
      name: muallimah
      driver: bridge   