version: '3.9'
services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'saladin2098'
      MINIO_ROOT_PASSWORD: 'minio_pass'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
    networks:
      - muallimah

  migrate:
    image: migrate/migrate
    networks:
      - muallimah
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",   
                "postgres://postgres:00salom00@muallimah_db:5432/muallimah_db?sslmode=disable", 
                "up" ]
    depends_on:
      - postgres-db
   

  postgres-db:
    container_name: muallimah_db
    image: postgres:latest
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: 00salom00
      PGDATA: /data/postgres
      POSTGRES_DB: muallimah_db
    volumes:
      - db:/muallimah-database/muallimah-memory
    ports:
      - "5437:5432"
    networks:
      - muallimah
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5   


  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper_muallimah
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - muallimah

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka_muallimah
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    networks:
      - muallimah
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_muallimah:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_muallimah:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  course_service:
    container_name: muallimah_course
    build: .
    depends_on:
      - kafka
      - minio
      
    ports:
      - "50052:50052"
    networks:
      - muallimah    
volumes:
  minio:
  db:
# Docker Networks
networks:
  muallimah:
    external: true
    name: muallimah
    driver: bridge