// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: muallimah-submodule/protos/lesson.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LessonCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurseId     string `protobuf:"bytes,1,opt,name=CurseId,proto3" json:"CurseId,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	VideoUrl    string `protobuf:"bytes,4,opt,name=VideoUrl,proto3" json:"VideoUrl,omitempty"`
}

func (x *LessonCreateReq) Reset() {
	*x = LessonCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LessonCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonCreateReq) ProtoMessage() {}

func (x *LessonCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonCreateReq.ProtoReflect.Descriptor instead.
func (*LessonCreateReq) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_lesson_proto_rawDescGZIP(), []int{0}
}

func (x *LessonCreateReq) GetCurseId() string {
	if x != nil {
		return x.CurseId
	}
	return ""
}

func (x *LessonCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LessonCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LessonCreateReq) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type LessonGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CurseId     string `protobuf:"bytes,2,opt,name=CurseId,proto3" json:"CurseId,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	VideoUrl    string `protobuf:"bytes,5,opt,name=VideoUrl,proto3" json:"VideoUrl,omitempty"`
	CreatedAt   string `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
}

func (x *LessonGet) Reset() {
	*x = LessonGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LessonGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonGet) ProtoMessage() {}

func (x *LessonGet) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonGet.ProtoReflect.Descriptor instead.
func (*LessonGet) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_lesson_proto_rawDescGZIP(), []int{1}
}

func (x *LessonGet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LessonGet) GetCurseId() string {
	if x != nil {
		return x.CurseId
	}
	return ""
}

func (x *LessonGet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LessonGet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LessonGet) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *LessonGet) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type LessonUpt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	VideoUrl    string `protobuf:"bytes,3,opt,name=VideoUrl,proto3" json:"VideoUrl,omitempty"`
}

func (x *LessonUpt) Reset() {
	*x = LessonUpt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LessonUpt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonUpt) ProtoMessage() {}

func (x *LessonUpt) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonUpt.ProtoReflect.Descriptor instead.
func (*LessonUpt) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_lesson_proto_rawDescGZIP(), []int{2}
}

func (x *LessonUpt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LessonUpt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LessonUpt) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type LessonUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string     `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Body *LessonUpt `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *LessonUpdate) Reset() {
	*x = LessonUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LessonUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonUpdate) ProtoMessage() {}

func (x *LessonUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonUpdate.ProtoReflect.Descriptor instead.
func (*LessonUpdate) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_lesson_proto_rawDescGZIP(), []int{3}
}

func (x *LessonUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LessonUpdate) GetBody() *LessonUpt {
	if x != nil {
		return x.Body
	}
	return nil
}

type LessonList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lessons    []*LessonGet `protobuf:"bytes,1,rep,name=Lessons,proto3" json:"Lessons,omitempty"`
	Count      int32        `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Pagination *Pagination  `protobuf:"bytes,3,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
}

func (x *LessonList) Reset() {
	*x = LessonList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LessonList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonList) ProtoMessage() {}

func (x *LessonList) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonList.ProtoReflect.Descriptor instead.
func (*LessonList) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_lesson_proto_rawDescGZIP(), []int{4}
}

func (x *LessonList) GetLessons() []*LessonGet {
	if x != nil {
		return x.Lessons
	}
	return nil
}

func (x *LessonList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LessonList) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type LessonFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseId string      `protobuf:"bytes,1,opt,name=CourseId,proto3" json:"CourseId,omitempty"`
	Filter   *Pagination `protobuf:"bytes,2,opt,name=Filter,proto3" json:"Filter,omitempty"`
}

func (x *LessonFilter) Reset() {
	*x = LessonFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LessonFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonFilter) ProtoMessage() {}

func (x *LessonFilter) ProtoReflect() protoreflect.Message {
	mi := &file_muallimah_submodule_protos_lesson_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonFilter.ProtoReflect.Descriptor instead.
func (*LessonFilter) Descriptor() ([]byte, []int) {
	return file_muallimah_submodule_protos_lesson_proto_rawDescGZIP(), []int{5}
}

func (x *LessonFilter) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *LessonFilter) GetFilter() *Pagination {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_muallimah_submodule_protos_lesson_proto protoreflect.FileDescriptor

var file_muallimah_submodule_protos_lesson_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6d, 0x75, 0x61, 0x6c, 0x6c, 0x69, 0x6d, 0x61, 0x68, 0x2d, 0x73, 0x75, 0x62, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6c, 0x65, 0x73,
	0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x1a, 0x27, 0x6d, 0x75, 0x61, 0x6c, 0x6c, 0x69, 0x6d, 0x61, 0x68, 0x2d, 0x73, 0x75, 0x62,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x0f, 0x4c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x72, 0x6c, 0x22, 0xa5, 0x01, 0x0a, 0x09, 0x4c, 0x65,
	0x73, 0x73, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x75, 0x72, 0x73, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x75, 0x72, 0x73, 0x65, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x5d, 0x0a, 0x09, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x55, 0x70, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x72, 0x6c,
	0x22, 0x45, 0x0a, 0x0c, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x25, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x55, 0x70,
	0x74, 0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x83, 0x01, 0x0a, 0x0a, 0x4c, 0x65, 0x73, 0x73,
	0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x07, 0x4c, 0x65, 0x73, 0x73,
	0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x0a, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x56, 0x0a,
	0x0c, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x32, 0x8d, 0x02, 0x0a, 0x0d, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x2c,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x12, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x12, 0x32, 0x0a, 0x0c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64,
	0x12, 0x2a, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0b,
	0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x65, 0x73, 0x73, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x18, 0x5a, 0x16, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_muallimah_submodule_protos_lesson_proto_rawDescOnce sync.Once
	file_muallimah_submodule_protos_lesson_proto_rawDescData = file_muallimah_submodule_protos_lesson_proto_rawDesc
)

func file_muallimah_submodule_protos_lesson_proto_rawDescGZIP() []byte {
	file_muallimah_submodule_protos_lesson_proto_rawDescOnce.Do(func() {
		file_muallimah_submodule_protos_lesson_proto_rawDescData = protoimpl.X.CompressGZIP(file_muallimah_submodule_protos_lesson_proto_rawDescData)
	})
	return file_muallimah_submodule_protos_lesson_proto_rawDescData
}

var file_muallimah_submodule_protos_lesson_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_muallimah_submodule_protos_lesson_proto_goTypes = []any{
	(*LessonCreateReq)(nil), // 0: protos.LessonCreateReq
	(*LessonGet)(nil),       // 1: protos.LessonGet
	(*LessonUpt)(nil),       // 2: protos.LessonUpt
	(*LessonUpdate)(nil),    // 3: protos.LessonUpdate
	(*LessonList)(nil),      // 4: protos.LessonList
	(*LessonFilter)(nil),    // 5: protos.LessonFilter
	(*Pagination)(nil),      // 6: protos.Pagination
	(*ById)(nil),            // 7: protos.ById
	(*Void)(nil),            // 8: protos.Void
}
var file_muallimah_submodule_protos_lesson_proto_depIdxs = []int32{
	2, // 0: protos.LessonUpdate.Body:type_name -> protos.LessonUpt
	1, // 1: protos.LessonList.Lessons:type_name -> protos.LessonGet
	6, // 2: protos.LessonList.Pagination:type_name -> protos.Pagination
	6, // 3: protos.LessonFilter.Filter:type_name -> protos.Pagination
	0, // 4: protos.LessonService.CreateLesson:input_type -> protos.LessonCreateReq
	7, // 5: protos.LessonService.GetLesson:input_type -> protos.ById
	3, // 6: protos.LessonService.UpdateLesson:input_type -> protos.LessonUpdate
	7, // 7: protos.LessonService.DeleteLesson:input_type -> protos.ById
	5, // 8: protos.LessonService.ListLessons:input_type -> protos.LessonFilter
	8, // 9: protos.LessonService.CreateLesson:output_type -> protos.Void
	1, // 10: protos.LessonService.GetLesson:output_type -> protos.LessonGet
	8, // 11: protos.LessonService.UpdateLesson:output_type -> protos.Void
	8, // 12: protos.LessonService.DeleteLesson:output_type -> protos.Void
	4, // 13: protos.LessonService.ListLessons:output_type -> protos.LessonList
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_muallimah_submodule_protos_lesson_proto_init() }
func file_muallimah_submodule_protos_lesson_proto_init() {
	if File_muallimah_submodule_protos_lesson_proto != nil {
		return
	}
	file_muallimah_submodule_protos_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_muallimah_submodule_protos_lesson_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LessonCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_lesson_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LessonGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_lesson_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LessonUpt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_lesson_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LessonUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_lesson_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LessonList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_muallimah_submodule_protos_lesson_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LessonFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_muallimah_submodule_protos_lesson_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_muallimah_submodule_protos_lesson_proto_goTypes,
		DependencyIndexes: file_muallimah_submodule_protos_lesson_proto_depIdxs,
		MessageInfos:      file_muallimah_submodule_protos_lesson_proto_msgTypes,
	}.Build()
	File_muallimah_submodule_protos_lesson_proto = out.File
	file_muallimah_submodule_protos_lesson_proto_rawDesc = nil
	file_muallimah_submodule_protos_lesson_proto_goTypes = nil
	file_muallimah_submodule_protos_lesson_proto_depIdxs = nil
}
